### ISSUE TITLE
Versioning for input files

### ISSUE THREAD

**Issue by Luthaf** [Luthaf/cymbalum#13]
All the YAML files should have a `version` key for indicating the version of the input format. This will prevent strange bugs and incompatibility when updating input format.

```yaml
version: 1.0

pairs:
      - atoms: [O, O] 
        ...
```
