### ISSUE TITLE
Input files

### ISSUE THREAD

**Issue by Luthaf** [Luthaf/cymbalum#22]
This is a big issue, and I have been thinking a bit around it.

# Requirements

1. We need input files, because not every one wants to write code just to run a simulation;
2. We need nice input files, which are easy to read and modify without going back and forth to the documentation;
3. We need to be able to use the same input files when using cymbalum as a library, either directly in Rust, or with some kind of scripting language (probably Python);
4. The input files should use a pre-existing format;
5. As a bonus, the users should also be able to register new potentials, moves, etc. for parsing.

1 and 3 should not be controversial, and 2 means that input files should look a bit more like 
```
pairs: atoms = [O O], lj = sigma 3.5 A, epsilon = 122K
```
Than like this
```
&potp \
3 3 3.5 122 lj
;
```

About 4, as I plan to integrate a scripting language, there is no need for some ad-hoc scripting language to drive the simulation. A pre-existing language might be more familiar to users, easier to read in most of the cases, will have syntactic highlight in text editors and will be easier to validate without running the simulation.

At this point, [JSON](https://learnxinyminutes.com/docs/json/) is ruled out because it does not support comments, and is a bit too clumsy with `""` around the keys. INI is nice but not standardized. [YAML](https://learnxinyminutes.com/docs/yaml/) is very good, but has two problems: it is whitespace sensitive (which can confuse the users, see #5 for a wanted workaround), and nest a bit deeply for molecular simulations.

I thing I'll go with [TOML](https://github.com/toml-lang/toml), which is clean, simple and readable.

# Actual syntax

This [gist](https://gist.github.com/Luthaf/abea51dd0430d3cbf801) showcases a possible syntax for TOML input files. it is mainly separated in two sections:

## Interactions input

This is demonstrated [here](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-potentials-toml). We may want to remove the `type` section, and use something like this:

```toml
[[pairs]]
atoms = ["O", "O"]
lj = {sigma = "3.4 A", epsilon = "0.155 kJ/mol"}
```

This would allow for potentials to be inside inline tables:

```toml
pairs = [
    {atoms = ["O", "O"], lj = {sigma = "3.4 A", epsilon = "0.155 kJ/mol"}},
    {atoms = ["O", "H"], lj = {sigma = "2.1 A", epsilon = "0.085 kJ/mol"}},
]
```

## Simulation and systems input

There are multiple examples for the syntax:
- [An highly commented example](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-commented-toml)
- [Molecular dynamics](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-moleculardynamics-toml)
- [Monte-Carlo](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-montecarlo-toml)

One of the key points is that `systems` and `simulations` entry are arrays. That allow to have more than one system to apply some simulation to (think replica-exchange simulations, or [gibbs ensemble](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-multiple-systems-toml) Monte-Carlo); or to apply multiple simulation to one system: [like here](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-multiple-simulations-toml).

I might want to remove the `type` keyword here too, to replace 

```toml
[[simulations]]
nsteps = 10_000_000
outputs = [
    {type = "Trajectory", file = "filename.xyz", frequency = 100},
    {type = "Properties", file = "averages.dat", frequency = 100}
]
```

with 

```toml
[[simulations]]
nsteps = 10_000_000
outputs = [
    {trajectory = {file = "filename.xyz", frequency = 100}},
    {properties = {file = "averages.dat", frequency = 100}}
]
```

Or [this](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-montecarlo-toml-L15-L22) with

```toml
[[simulations.propagator]]
type = "MonteCarlo"
moves = [
    {translate = {delta = "1 A", proba = 50}},
    {rotate = {delta = "20 deg", proba = 50}},
    {resize = {proba = 1}},
]
```

We probably do not want to remove it from everywhere, for example 

```toml
[[simulations.propagator.moleculardynamics]]
timestep = "1 fs"
integrator = {berendsen_barostat = {pressure = "100 bar", timestep = "10000 fs"}}
thermostat = {berendsen = {temperature = "400 K", timestep = "1000 fs"}}
```

Feels readable than the [original version](https://gist.github.com/Luthaf/abea51dd0430d3cbf801#file-multiple-simulations-toml-L24-L28).

# Unresolved questions

- Is TOML good enough as input format?
- Should the `type` section be removed? If yes, where? It appears in potentials, in lists of `outputs` or `moves`, and as keyword for `propagator`, `thermostat`, ...

**Comment by Luthaf** [comment]
@g-bauer @Scioratis, I'd like to have your input on this !

**Comment by g-bauer** [comment]
I think TOML is a nice choice.

Regarding the `type` section: I think it can be a good idea to leave it in the files. For people that are not familiar with the format the `type = "..."` clearly signals where they need to put in keywords (or values). Also, you don't need the nested curly braces which is always easier to read. The nested tables are neat, but there is more room to produce errors. On the other hand, input files would become very big for a huge number of different interactions.

For me, both would work fine.

**Comment by Luthaf** [comment]
The nested curly braces are effectively not optimal. But I still prefer 

```toml
[[pairs]]
atoms = ["O", "O"]
lj = {sigma = "3.4 A", epsilon = "0.155 kJ/mol"}
```

to

```toml
[[pairs]]
atoms = ["O", "O"]
type = "LennardJones"
sigma = "3.4 A"
epsilon = "0.155 kJ/mol"
```

How about removing `type` in potentials, and keeping it for the systems/simulations inputs?

**Comment by g-bauer** [comment]
I agree, for potentials the proposed solution without `type` is more convenient. I'd go with leaving the `type` in the simulation and systems parts, since from what I can see in your examples, these parts are still readable and not too big.

**Comment by Luthaf** [comment]
I have got an initial implementation of the potential input files in the `input-toml` branch. The documentation still needs to be updated before merging it. The system/simulation input files will need more work.

A question that I got during the implementation: how to handle the `Null` potential ?
I feels nice using a boolean value:
```toml
[[pairs]]
atoms = ["A", "B"]
null = true
```

But all other potentials uses tables, and while the `Null` potential is a bit special, I don't know if using a different input style is worth it.

```toml
# the other option is to use an empty table
[[pairs]]
atoms = ["A", "B"]
null = {}
```
