### ISSUE TITLE
Add combining rules for intermolecular interaction parameters

### ISSUE THREAD

**Issue by g-bauer** [Luthaf/cymbalum#33]
It would be very convenient to have combining rules. For example, specify in the input:

```toml
[input]
version = 1

[[pairs]]
atoms = ["A", "A"]
lj = {sigma = "... ", epsilon = ..."}

[[pairs]]
atoms = ["B", "B"]
lj = {sigma = "... ", epsilon = ..."}

[mixing-rule]
atoms = ["A", "B"]
type = LB # LB = Lorentz-Berthelot
```                                      

As an option, one would not need to specify A,B pair interactions. Instead, a combining rule is applied. Another possibility is to make the combining rule "global", i.e.: 

```toml
[input]
version = 1

[[pairs]]
atoms = ["A", "A"]
lj = {sigma = "... ", epsilon = ..."}

[[pairs]]
atoms = ["B", "B"]
lj = {sigma = "... ", epsilon = ..."}

# the rule is applied to all intermolec. interactions
[combining-rule]
type = LB # LB = Lorentz-Berthelot
```

**Comment by Luthaf** [comment]
I agree this is nice to have, but I would not add a separated table for that. As combining rules mainly (only?) make sense for Lennard-Jones, we can reuse the `lj` key:

```toml
[input]
version = 1

[[pairs]]
atoms = ["A", "A"]
lj = {sigma = "... ", epsilon = ..."}

[[pairs]]
atoms = ["B", "B"]
lj = {sigma = "... ", epsilon = ..."}

[[pairs]]
atoms = ["A", "B"]
# Use previously defined parameters here
lj = {combine = "LorentzBerthelot"}
```

That plus #7 allow to use combining rules for all unspecified parameters:

```toml
[[pairs]]
atoms = ["*", "*"]
lj = {combine = "LorentzBerthelot"}
```
